Ecomm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "store" 

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product/<int:pk>', views.product_detail, name='product_detail'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('cart/', views.view_cart, name='view_cart'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('track/', views.track, name='track'),
    path('category/<str:category>', views.category, name='category'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    
    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='products', null=True, blank=True)

    def __str__(self) -> str:
        return self.name
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)

    def __str__(self) -> str:
        return self.user.username

class Status(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    orderdate = models.DateField(default=date.today)
    isdelivered = models.BooleanField(default=False)
    isoutfordelivery = models.BooleanField(default=False)
    isshipped = models.BooleanField(default=False)
    isordered = models.BooleanField(default=True)

    def __str__(self):
        return f"Order {self.pk}"

store/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'}), label='Username')

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'}), label='Password')


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        'class': 'w-full py-4 px-6 rounded-xl'}))

store/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from .models import Product, Category, Cart
from .models import Status
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import SignupForm, LoginForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def product_list(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    if request.user.is_authenticated:
        myorders = Status.objects.filter(user=request.user)
        return render(request, 'store/product_list.html',{'products': products, 'categories':categories, 'myorders':myorders})
    return render(request, 'store/product_list.html',{'products': products, 'categories':categories})

def product_detail(request, pk):
    product = get_list_or_404(Product, pk=pk)[0]
    buy = True
    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user)
        products = cart.products.all()
        if product in products:
            buy=False
        return render(request, 'store/product_detail.html',{'product': product, 'buy': buy})
    return render(request, 'store/product_detail.html',{'product': product, 'buy': buy})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            password1 = form.cleaned_data.get("password1")
            user = authenticate(username=username,password=password1)
            login(request,user)        
            return redirect('/')
        else:
            a=dict()
            a['form'] = form
            return render(request, 'store/signup.html', context=a)
    else:
        form = SignupForm()   
    a=dict()
    a['form'] = form
    return render(request, 'store/signup.html', context=a)


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            form = LoginForm()
    else:
        form = LoginForm()

    return render(request, "store/login.html", {'form': form})

def logout_view(request):
    logout(request)
    return redirect('/')

@login_required(login_url='store:login')
def view_cart(request):
    cart, created = Cart.objects.get_or_create(user=request.user)
    products = cart.products.all()
    total = 0
    for i in products:
        total += i.price
    return render(request, 'store/cart.html', {'products': products, 'total': total})

@login_required(login_url='store:login')
def add_to_cart(request, product_id):
    product = Product.objects.get(pk=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart.products.add(product)
    return redirect('store:view_cart')

@login_required(login_url='store:login')
def remove_from_cart(request, product_id):
    product = Product.objects.get(pk=product_id)
    cart = Cart.objects.get(user=request.user)
    cart.products.remove(product)
    return redirect('store:view_cart')

@login_required(login_url='store:login')
def checkout(request):
    if request.method == 'POST':
        cart, created = Cart.objects.get_or_create(user=request.user)
        products = cart.products.all()
        for i in products:
            x = Status(user=request.user, product=i)
            x.save()
            # x.product.add(i)
            cart.products.remove(i)
            
        return redirect('store:track')
    
    cart, created = Cart.objects.get_or_create(user=request.user)
    products = cart.products.all()
    total = 0
    for i in products:
        total += i.price
    return render(request, 'store/checkout.html', {'total': total})

@login_required(login_url='store:login')
def track(request):
    myorders = Status.objects.filter(user=request.user)
    return render(request, 'store/track.html', {'orders': myorders})

def category(request, category):
    category = get_object_or_404(Category, name=category)
    products = Product.objects.filter(category=category)
    categories = Category.objects.all()
    if request.user.is_authenticated:
        myorders = Status.objects.filter(user=request.user)
        return render(request, 'store/category.html',{'products': products, 'myorders':myorders, 'name': category, 'categories':categories})
    return render(request, 'store/category.html',{'products': products, 'name': category, 'categories':categories})

def about(request):
    return render(request, 'store/aboutme.html')

def contact(request):
    return render(request, 'store/contact.html')

store/templates/store/aboutme.html
{% extends 'store/base.html' %}

{% block title %}
    About Me
{% endblock %}

{% block content %}
    <div class="container mx-auto px-4 py-8">
        <div class="max-w-3xl mx-auto bg-white rounded p-8 shadow-md">
            <h2 class="text-2xl font-bold mb-6 text-center">About Me</h2>
            <div class="flex items-center">
                <img src="path_to_profile_image.jpg" alt="Profile Image" class="w-24 h-24 rounded-full mr-4">
                <div>
                    <h3 class="text-lg font-semibold">Ishan Chauhan</h3>
                    <p class="text-gray-500">Full Stack Developer</p>
                </div>
            </div>
            <p class="mt-4">Hello, I'm Ishan Chauhan, a passionate developer and a proud member of the [Your Company/Brand] team. I love building innovative solutions and creating seamless online experiences.</p>
<p class="mt-4">With a strong background in web development, I specialize in crafting user-friendly interfaces and robust backend systems. From conceptualizing ideas to turning them into reality, I enjoy the entire development lifecycle.</p>
<p class="mt-4">I have expertise in various programming languages and frameworks, including HTML, CSS, JavaScript, Python, and Django. I stay updated with the latest industry trends and best practices to deliver cutting-edge solutions.</p>
<p class="mt-4">Collaboration is a key aspect of my work. I enjoy working with cross-functional teams, designers, and stakeholders to ensure that the projects meet the highest standards of quality and exceed client expectations.</p>
<p class="mt-4">When I'm not coding, you can find me exploring new technologies, experimenting with side projects, and continuously learning to enhance my skills. I'm driven by the desire to create innovative solutions that make a positive impact.</p>
<p class="mt-4">I'm excited contribute to our mission of delivering exceptional online experiences. If you have any questions or need assistance, feel free to reach out. Let's create something amazing together!</p>


        </div>
    </div>
{% endblock %}

store/templates/store/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{%block title%} {%endblock%} | EComm</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">EComm</a>
        <div class="space-x-6">
            {%if request.user.is_authenticated%}
            <a href="{%url 'store:track' %}" class="px-6 py-3 text-lg font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-700">My Orders</a>
            <a href="{%url 'store:logout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log Out</a>
            <a href="{%url 'store:view_cart' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">@{{request.user.username}}'s cart</a>
            {%else%}  
            <a href="{%url 'store:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="{%url 'store:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">LogIn</a>
            {%endif%}
        </div>
    </nav>
    <div class="px-6 py-6">
        {%block content%}
        {%endblock%}
    </div>
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About Project</h3>
            <p class="text-lg text-gray-500">My ecommerce project in Django is a robust and user-friendly platform that enables customers to browse, search, and purchase a wide range of products. With secure user authentication, and seamless shopping cart system, it ensures a smooth experience. The project also includes features such as product categorization, order tracking, and a responsive design for optimal usability across devices. Built with scalability in mind, it offers a customizable admin panel for easy product management and inventory control. Overall, the Django-based ecommerce project delivers a reliable and efficient online shopping experience.</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="{%url 'store:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact Me</a></li>
                <li><a href="{%url 'store:about' %}" class="text-lg text-teal-500 hover:text-teal-700">About Me</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

store/templates/store/cart.html
{% extends 'store/base.html'%}

{%block title%}
Cart
{% endblock %}

{%block content%}

<!-- <h1>Cart</h1>
  <ul id="cart-items">
    {% if products %}
      {% for product in products %}
        <li class="cart-item">
          <span class="product-name">{{ product.name }}</span>
          <span class="product-price">₹{{ product.price }}</span>
        </li>
      {% endfor %}
    {% else %}
      <li class="empty-cart">Your cart is empty.</li>
    {% endif %}
  </ul> -->

<div class="container mx-auto p-4">
  <h1 class="text-3xl font-bold mb-4">Cart</h1>
  {% if products %}
  <div class="bg-white p-4 shadow rounded">
    <ul class="divide-y divide-gray-200">

      <!-- Cart item -->
      {% for product in products %}
      <li class="flex items-center py-2">
        <div class="flex-shrink-0">
          <img class="w-20 h-20 rounded" src="{{product.img.url}}" alt="Product">
        </div>
        <div class="ml-4">
          <h2 class="text-lg font-semibold">{{ product.name }}</h2>
          <p class="text-gray-600">Price: ₹<span class="price">{{ product.price }}</span></p>
        </div>
        <a href="{%url 'store:remove_from_cart' product.id%}" class="ml-auto text-red-500 hover:text-red-600">
          Remove
        </a>
      </li>
    </ul>
    {% endfor %}
    <div class="mt-4">
      <p class="text-lg font-semibold">
        Total: ₹{{total}}
      </p>
      <br>
      <a href="{%url 'store:checkout'%}" class="mt-4 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600" role="button">
        Checkout
      </a>
    </div>
  </div>
  {% else %}
  <li class="empty-cart">Your cart is empty.</li>
  {% endif %}
</div>


{%endblock%}

store/templates/store/category.html
{% extends 'store/base.html'%}

{%block title%}
    Welcome
{% endblock %}

{%block content%}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">{{name}}</h2>
        <div class="grid grid-cols-3 gap-3">
            {%for product in products%}
            <div class="border-2">
                <a href="{%url 'store:product_detail' product.id%}">
                    <div class="flex justify-center">
                        <img src="{{product.img.url}}" alt="img1" class="rounded-t-xl" style="height: 250px; width: 70%;">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{product.name}}</h2>
                        <p class="text-gray-500">Price: ₹{{product.price}}</p>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {%for category in categories%}
            <div>
                <a href="{%url 'store:category' category.name%}">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{category.name}}</h2>
                        <p class="text-gray-500">{{category.product_set.count}} products</p>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>

{%endblock%}

store/templates/store/checkout.html
{% extends 'store/base.html'%}

{%block title%}
Checkout
{% endblock %}

{%block content%}

<div class="container mx-auto px-4 py-8">
    <div class="max-w-md mx-auto bg-white rounded p-8 shadow-md">

        <h2 class="text-2xl font-bold mb-6">Checkout</h2>

        <form action="." method="post"  enctype="multipart/form-data">

            {%csrf_token%}

            <div class="mb-4">
                <label for="name" class="block mb-2 text-sm font-bold">Name</label>
                <input type="text" id="name" name="name" class="w-full px-3 py-2 border border-gray-300 rounded"
                    required>
            </div>

            <div class="mb-4">
                <label for="email" class="block mb-2 text-sm font-bold">Email</label>
                <input type="email" id="email" name="email" class="w-full px-3 py-2 border border-gray-300 rounded"
                    required>
            </div>

            <div class="mb-4">
                <label for="address" class="block mb-2 text-sm font-bold">Address</label>
                <textarea id="address" name="address" rows="3" class="w-full px-3 py-2 border border-gray-300 rounded"
                    required></textarea>
            </div>

            <div class="mb-4">
                <label for="cardNumber" class="block mb-2 text-sm font-bold">Card Number</label>
                <input type="text" id="cardNumber" name="cardNumber"
                    class="w-full px-3 py-2 border border-gray-300 rounded" required>
            </div>

            <div class="mb-4">
                <label for="expiry" class="block mb-2 text-sm font-bold">Expiry</label>
                <input type="text" id="expiry" name="expiry" class="w-full px-3 py-2 border border-gray-300 rounded"
                    required>
            </div>

            <div class="mb-4">
                <label for="cvv" class="block mb-2 text-sm font-bold">CVV</label>
                <input type="text" id="cvv" name="cvv" class="w-full px-3 py-2 border border-gray-300 rounded" required>
            </div>

            <div class="mt-4">
                <p class="text-lg font-semibold">
                    Total: ₹{{total}}
                </p>
            </div>

            <br>

            <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">Place
                Order</button>
        </form>

    </div>
</div>

{%endblock%}

store/templates/store/contact.html
{% extends 'store/base.html' %}

{% block title %}
    About Me
{% endblock %}

{% block content %}

<div class="container mx-auto px-4 py-8">
    <div class="max-w-3xl mx-auto bg-white rounded p-8 shadow-md">
        <h2 class="text-2xl font-bold mb-6 text-center">Contact Me</h2>
        
        <form action="/contact" method="post" class="mt-4">
            <div class="mb-4">
                <label for="name" class="block text-gray-700 font-medium mb-2">Your Name</label>
                <input type="text" id="name" name="name" class="w-full px-4 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500" required>
            </div>
            <div class="mb-4">
                <label for="email" class="block text-gray-700 font-medium mb-2">Email Address</label>
                <input type="email" id="email" name="email" class="w-full px-4 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500" required>
            </div>
            <div class="mb-4">
                <label for="message" class="block text-gray-700 font-medium mb-2">Message</label>
                <textarea id="message" name="message" rows="5" class="w-full px-4 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500" required></textarea>
            </div>
            <div class="text-center">
                <button type="submit" class="px-6 py-2 bg-indigo-500 text-white font-bold rounded hover:bg-indigo-700">Send Message</button>
            </div>
        </form>
    </div>
</div>

{%endblock%}

store/templates/store/login.html
{%extends 'store/base.html'%}

{%block title%}
LogIn
{%endblock%}

{%block content%}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="mb-6 text-3xl">
    <center>LogIn</center>
  </h1>

  <form action="." method="post" enctype="multipart/form-data">

    {%csrf_token%}

    {%if form.errors or form.non_feild_errors%}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
      {%for feild in form%}
      {{feild.errors}}
      {%endfor%}
      {{form.non_field_errors}}
    </div>
    {%endif%}

    <div class="mb-3">
      <label for="" class="inline-block mb-2">Username</label><br>
      {{form.username}}
  </div>

  <div class="mb-3">
      <label for="" class="inline-block mb-2">Password</label><br>
      {{form.password}}
  </div>

    <br>
    <center>
      <button type="submit" id='submit-button'
        class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </center>
  </form>
</div>


{%endblock%}

store/templates/store/product_detail.html
{% extends 'store/base.html'%}

{%block title%}
{{product.name}}
{%endblock%}

{%block content%}
<div class="grid grid-cols-5 gap-6">

    <div class="col-span-3">
        <img src="{{product.img.url}}" alt="img1" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{product.name}}</h1>
        <p class="text-gray-500"><strong>Price: </strong>₹{{product.price}}</p>

        {%if product.description%}
        <p class="text-gray-700">
            <strong class="text-gray-500">Description</strong><br>
            {{product.description}}
        </p>
        {%endif%}

        <br>

        <form action="." method="post">
            {%csrf_token%}
            {%if buy%}
            <a href="{%url 'store:add_to_cart' product.id%}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Add to Cart</a>
            {%else%}
            <a href="{%url 'store:remove_from_cart' product.id%}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Remove from Cart</a>
            {%endif%}
        </form>
    </div>
</div>

{%if related_products%}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Similar Products</h2>
    <div class="grid grid-cols-3 gap-3">
        {%for product in related_products%}
        <div class="border-2">
            <a href="{%url 'product:detail' product.id%}">
                <div class="flex justify-center">
                    <img src="{{product.img.url}}" alt="img1" class="rounded-t-xl" style="height: 250px; width: 70%;">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{product.name}}</h2>
                    <p class="text-gray-500">Price: ₹{{product.price}}</p>
                </div>
            </a>
        </div>
        {%endfor%}
    </div>
</div>
{%endif%}

{%endblock%}

store/templates/store/product_list.html
{% extends 'store/base.html'%}

{%block title%}
    Welcome
{% endblock %}

{%block content%}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">All Products</h2>
        <div class="grid grid-cols-3 gap-3">
            {%for product in products%}
            <div class="border-2">
                <a href="{%url 'store:product_detail' product.id%}">
                    <div class="flex justify-center">
                        <img src="{{product.img.url}}" alt="img1" class="rounded-t-xl" style="height: 250px; width: 70%;">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{product.name}}</h2>
                        <p class="text-gray-500">Price: ₹{{product.price}}</p>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {%for category in categories%}
            <div>
                <a href="{%url 'store:category' category.name%}">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{category.name}}</h2>
                        <p class="text-gray-500">{{category.product_set.count}} products</p>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>

{%endblock%}

store/templates/store/signup.html
{%extends 'store/base.html'%}

{%block title%}
Sign Up
{%endblock%}

{%block content%}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>
    <form action="." method="post"  enctype="multipart/form-data">

        {%csrf_token%}
        {{form.non_field_errors}}

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Username</label><br>
            {{form.username}}
        </div>

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Email</label><br>
            {{form.email}}
        </div>

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Password</label><br>
            {{form.password1}}
        </div>

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Confirm Password</label><br>
            {{form.password2}}
        </div>

        {%if form.errors or form.non_feild_errors%}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {%for feild in form%}
                {{feild.errors}}
            {%endfor%}
        </div>
        {%endif%}
        <br>
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{%endblock%}

store/templates/store/track.html
{% extends 'store/base.html'%}

{%block title%}
    Track
{% endblock %}

{%block content%}
<div class="container mx-auto px-4 py-8">
    <div class="max-w-3xl mx-auto bg-white rounded p-8 shadow-md">

      <h2 class="text-2xl font-bold mb-6 text-center">Tracking Status</h2>

      <div class="mt-8">
        <h3 class="text-lg font-bold mb-2">Product Status Updates</h3>
        <table class="w-full">
          <thead>
            <tr>
              <th class="py-2">Product</th>
              <th class="py-2">Last Update</th>
            </tr>
          </thead>
          <tbody>
            {%for order in orders%}
              {%if order.isdelivered%}
              <tr class="bg-green-200">
                <td class="py-2 text-center">{{order.product.name}}</td>
                <td class="py-2 text-center">Package delivered to recipient.</td>
              {%elif order.isoutfordelivery%}
              <tr class="bg-yellow-200">
                <td class="py-2 text-center">{{order.product.name}}</td>
                <td class="py-2 text-center">Package out for delivery.</td>
              {%elif order.isshipped%}
              <tr class="bg-yellow-300">
                <td class="py-2 text-center">{{order.product.name}}</td>
                <td class="py-2 text-center">Package shipped from origin.</td>
              {%else%}
              <tr class="bg-gray-200">
                <td class="py-2 text-center">{{order.product.name}}</td>
                <td class="py-2 text-center">Package ordered</td>
              {%endif%}
            </tr>
            {%endfor%}
            <!-- <tr class="bg-yellow-200">
              <td class="py-2 text-center">Product 2</td>
              <td class="py-2 text-center">Package shipped from origin.</td>
            </tr>
            <tr class="bg-yellow-300">
              <td class="py-2 text-center">Product 3</td>
              <td class="py-2 text-center">Package out for delivery.</td>
            </tr>
            <tr class="bg-green-200">
              <td class="py-2 text-center">Product 4</td>
              <td class="py-2 text-center">Package delivered to recipient.</td>
            </tr> -->
          </tbody>
        </table>
      </div>

    </div>
  </div>

  {%endblock%}